var hierarchy =
[
    [ "AbsClass", "classAbsClass.html", [
      [ "InsClass", "classInsClass.html", null ]
    ] ],
    [ "acpi::Acpi", "classacpi_1_1Acpi.html", null ],
    [ "Apic", "classApic.html", null ],
    [ "atexit_func_entry_t", "structatexit__func__entry__t.html", null ],
    [ "virtio::SplitVirtqueue::Avail", "structvirtio_1_1SplitVirtqueue_1_1Avail.html", null ],
    [ "BasicInfo", "structBasicInfo.html", null ],
    [ "virtio::blk::BlkConfig", "structvirtio_1_1blk_1_1BlkConfig.html", null ],
    [ "virtio::blk::BlkDiscardWriteZeroes", "structvirtio_1_1blk_1_1BlkDiscardWriteZeroes.html", null ],
    [ "virtio::blk::BlkLifetime", "structvirtio_1_1blk_1_1BlkLifetime.html", null ],
    [ "virtio::blk::BlkReqHeader", "structvirtio_1_1blk_1_1BlkReqHeader.html", null ],
    [ "vfs::BlockDevice", "classvfs_1_1BlockDevice.html", [
      [ "virtio::blk::VirtioBlkVfsAdapter", "classvirtio_1_1blk_1_1VirtioBlkVfsAdapter.html", null ]
    ] ],
    [ "cpu_io::CalleeSavedContext", "structcpu__io_1_1CalleeSavedContext.html", null ],
    [ "test_env::CoreEnvironment", "structtest__env_1_1CoreEnvironment.html", null ],
    [ "CpuSchedData", "structCpuSchedData.html", null ],
    [ "CStrLess", "structCStrLess.html", null ],
    [ "vfs::Dentry", "structvfs_1_1Dentry.html", null ],
    [ "virtio::SplitVirtqueue::Desc", "structvirtio_1_1SplitVirtqueue_1_1Desc.html", null ],
    [ "acpi::Acpi::DescriptionHeader", "structacpi_1_1Acpi_1_1DescriptionHeader.html", null ],
    [ "virtio::DeviceInitializer< TransportImpl >", "classvirtio_1_1DeviceInitializer.html", null ],
    [ "DeviceManager", "classDeviceManager.html", null ],
    [ "DeviceNode", "structDeviceNode.html", null ],
    [ "vfs::DirEntry", "structvfs_1_1DirEntry.html", null ],
    [ "DmaRegion", "structDmaRegion.html", null ],
    [ "DriverEntry", "structDriverEntry.html", null ],
    [ "DriverRegistry", "classDriverRegistry.html", null ],
    [ "acpi::Acpi::Dsdt", "structacpi_1_1Acpi_1_1Dsdt.html", null ],
    [ "Error", "structError.html", null ],
    [ "acpi::Acpi::Fadt", "structacpi_1_1Acpi_1_1Fadt.html", null ],
    [ "fatfs::FatFsFileSystem::FatDirHandle", "structfatfs_1_1FatFsFileSystem_1_1FatDirHandle.html", null ],
    [ "fatfs::FatFsFileSystem::FatFileHandle", "structfatfs_1_1FatFsFileSystem_1_1FatFileHandle.html", null ],
    [ "fatfs::FatFsFileSystem::FatInode", "structfatfs_1_1FatFsFileSystem_1_1FatInode.html", null ],
    [ "vfs::File", "structvfs_1_1File.html", null ],
    [ "filesystem::FileDescriptorTable", "classfilesystem_1_1FileDescriptorTable.html", null ],
    [ "vfs::FileOps", "classvfs_1_1FileOps.html", [
      [ "MockFileOps", "classMockFileOps.html", null ],
      [ "fatfs::FatFsFileSystem::FatFsFileOps", "classfatfs_1_1FatFsFileSystem_1_1FatFsFileOps.html", null ],
      [ "ramfs::RamFs::RamFsFileOps", "classramfs_1_1RamFs_1_1RamFsFileOps.html", null ]
    ] ],
    [ "vfs::FileSystem", "classvfs_1_1FileSystem.html", [
      [ "MockFs", "classMockFs.html", null ],
      [ "fatfs::FatFsFileSystem", "classfatfs_1_1FatFsFileSystem.html", null ],
      [ "ramfs::RamFs", "classramfs_1_1RamFs.html", null ]
    ] ],
    [ "etl::fsm_state", null, [
      [ "StateBlocked", "structStateBlocked.html", null ],
      [ "StateExited", "structStateExited.html", null ],
      [ "StateReady", "structStateReady.html", null ],
      [ "StateRunning", "structStateRunning.html", null ],
      [ "StateSleeping", "structStateSleeping.html", null ],
      [ "StateUnInit", "structStateUnInit.html", null ],
      [ "StateZombie", "structStateZombie.html", null ]
    ] ],
    [ "acpi::Acpi::GenericAddressStructure", "structacpi_1_1Acpi_1_1GenericAddressStructure.html", null ],
    [ "Gic", "classGic.html", null ],
    [ "Gic::Gicd", "classGic_1_1Gicd.html", null ],
    [ "Gic::Gicd::GicdCtlr", "structGic_1_1Gicd_1_1GicdCtlr.html", null ],
    [ "Gic::Gicd::GicdIidr", "structGic_1_1Gicd_1_1GicdIidr.html", null ],
    [ "Gic::Gicd::GicdTyper", "structGic_1_1Gicd_1_1GicdTyper.html", null ],
    [ "Gic::Gicr", "classGic_1_1Gicr.html", null ],
    [ "GuardType", "structGuardType.html", null ],
    [ "etl::hash< ResourceId >", "structetl_1_1hash_3_01ResourceId_01_4.html", null ],
    [ "std::hash< ResourceId >", "structstd_1_1hash_3_01ResourceId_01_4.html", null ],
    [ "vfs::Inode", "structvfs_1_1Inode.html", null ],
    [ "vfs::InodeOps", "classvfs_1_1InodeOps.html", [
      [ "fatfs::FatFsFileSystem::FatFsInodeOps", "classfatfs_1_1FatFsFileSystem_1_1FatFsInodeOps.html", null ],
      [ "ramfs::RamFs::RamFsInodeOps", "classramfs_1_1RamFs_1_1RamFsInodeOps.html", null ]
    ] ],
    [ "InterruptBase", "classInterruptBase.html", [
      [ "Interrupt", "classInterrupt.html", null ],
      [ "Interrupt", "classInterrupt.html", null ],
      [ "Interrupt", "classInterrupt.html", null ]
    ] ],
    [ "TaskManager::InterruptWork", "structTaskManager_1_1InterruptWork.html", null ],
    [ "IoApic", "classIoApic.html", null ],
    [ "IoBuffer", "classIoBuffer.html", null ],
    [ "virtio::IoVec", "structvirtio_1_1IoVec.html", null ],
    [ "KernelElf", "classKernelElf.html", null ],
    [ "KernelFdt", "classKernelFdt.html", null ],
    [ "LocalApic", "classLocalApic.html", null ],
    [ "LockGuard< Mutex >", "classLockGuard.html", null ],
    [ "klog::detail::LogEntry", "structklog_1_1detail_1_1LogEntry.html", null ],
    [ "MatchEntry", "structMatchEntry.html", null ],
    [ "etl::message", null, [
      [ "MsgBlock", "structMsgBlock.html", null ],
      [ "MsgExit", "structMsgExit.html", null ],
      [ "MsgReap", "structMsgReap.html", null ],
      [ "MsgSchedule", "structMsgSchedule.html", null ],
      [ "MsgSleep", "structMsgSleep.html", null ],
      [ "MsgWakeup", "structMsgWakeup.html", null ],
      [ "MsgYield", "structMsgYield.html", null ],
      [ "ThreadCreateMsg", "structThreadCreateMsg.html", null ],
      [ "ThreadExitMsg", "structThreadExitMsg.html", null ]
    ] ],
    [ "MmioAccessor", "structMmioAccessor.html", null ],
    [ "vfs::MountPoint", "structvfs_1_1MountPoint.html", null ],
    [ "vfs::MountTable", "classvfs_1_1MountTable.html", null ],
    [ "Mutex", "classMutex.html", null ],
    [ "ns16550a::Ns16550a", "classns16550a_1_1Ns16550a.html", null ],
    [ "Ns16550aDriver", "classNs16550aDriver.html", null ],
    [ "PanicEvent", "structPanicEvent.html", null ],
    [ "param", "structparam.html", null ],
    [ "per_cpu::PerCpu", "structper__cpu_1_1PerCpu.html", null ],
    [ "pl011::Pl011", "classpl011_1_1Pl011.html", null ],
    [ "Pl011Driver", "classPl011Driver.html", null ],
    [ "PlatformBus", "classPlatformBus.html", null ],
    [ "Plic", "classPlic.html", null ],
    [ "TaskControlBlock::PriorityCompare", "structTaskControlBlock_1_1PriorityCompare.html", null ],
    [ "mmio_helper::ProbeContext", "structmmio__helper_1_1ProbeContext.html", null ],
    [ "ramfs::RamFs::RamDirEntry", "structramfs_1_1RamFs_1_1RamDirEntry.html", null ],
    [ "ramfs::RamFs::RamInode", "structramfs_1_1RamFs_1_1RamInode.html", null ],
    [ "virtio::blk::VirtioBlk< TransportT, VirtqueueT >::RequestSlot", "structvirtio_1_1blk_1_1VirtioBlk_1_1RequestSlot.html", null ],
    [ "ResourceId", "classResourceId.html", null ],
    [ "acpi::Acpi::Rsdp", "structacpi_1_1Acpi_1_1Rsdp.html", null ],
    [ "acpi::Acpi::Rsdt", "structacpi_1_1Acpi_1_1Rsdt.html", null ],
    [ "TaskControlBlock::SchedData", "unionTaskControlBlock_1_1SchedData.html", null ],
    [ "TaskControlBlock::SchedInfo", "structTaskControlBlock_1_1SchedInfo.html", null ],
    [ "SchedulerBase", "classSchedulerBase.html", [
      [ "CfsScheduler", "classCfsScheduler.html", null ],
      [ "FifoScheduler", "classFifoScheduler.html", null ],
      [ "IdleScheduler", "classIdleScheduler.html", null ],
      [ "RoundRobinScheduler", "classRoundRobinScheduler.html", null ]
    ] ],
    [ "SipiParams", "structSipiParams.html", null ],
    [ "SpinLock", "classSpinLock.html", null ],
    [ "SchedulerBase::Stats", "structSchedulerBase_1_1Stats.html", null ],
    [ "test_env::CoreEnvironment::SwitchEvent", "structtest__env_1_1CoreEnvironment_1_1SwitchEvent.html", null ],
    [ "TaskAuxData", "structTaskAuxData.html", null ],
    [ "TaskFsm", "classTaskFsm.html", null ],
    [ "TaskManager", "classTaskManager.html", null ],
    [ "testing::Test", null, [
      [ "BaseEnvTest", "classBaseEnvTest.html", [
        [ "FdTableTest", "classFdTableTest.html", null ],
        [ "MountTableTest", "classMountTableTest.html", null ],
        [ "VfsInitTest", "classVfsInitTest.html", null ]
      ] ],
      [ "KernelFdtTest", "classKernelFdtTest.html", null ],
      [ "RamFsTest", "classRamFsTest.html", null ],
      [ "TaskTestHarness", "classTaskTestHarness.html", null ],
      [ "VfsTest", "classVfsTest.html", null ]
    ] ],
    [ "test_env::TestEnvironmentState", "classtest__env_1_1TestEnvironmentState.html", null ],
    [ "TestResult", "structTestResult.html", null ],
    [ "TestStaticConstructDestruct< V >", "classTestStaticConstructDestruct.html", null ],
    [ "ThreadGroupLink", null, [
      [ "TaskControlBlock", "structTaskControlBlock.html", null ]
    ] ],
    [ "TickEvent", "structTickEvent.html", null ],
    [ "virtio::Transport", "classvirtio_1_1Transport.html", [
      [ "virtio::MmioTransport", "classvirtio_1_1MmioTransport.html", null ],
      [ "virtio::PciTransport", "classvirtio_1_1PciTransport.html", null ]
    ] ],
    [ "cpu_io::TrapContext", "structcpu__io_1_1TrapContext.html", null ],
    [ "virtio::SplitVirtqueue::Used", "structvirtio_1_1SplitVirtqueue_1_1Used.html", null ],
    [ "virtio::SplitVirtqueue::UsedElem", "structvirtio_1_1SplitVirtqueue_1_1UsedElem.html", null ],
    [ "vfs::VfsState", "structvfs_1_1VfsState.html", null ],
    [ "virtio::blk::VirtioBlk< TransportT, VirtqueueT >", "classvirtio_1_1blk_1_1VirtioBlk.html", null ],
    [ "VirtioDriver", "classVirtioDriver.html", null ],
    [ "virtio::blk::VirtioStats", "structvirtio_1_1blk_1_1VirtioStats.html", null ],
    [ "virtio::VirtqueueBase", "classvirtio_1_1VirtqueueBase.html", [
      [ "virtio::SplitVirtqueue", "classvirtio_1_1SplitVirtqueue.html", null ]
    ] ],
    [ "VirtualMemory", "classVirtualMemory.html", null ],
    [ "CfsScheduler::VruntimeCompare", "structCfsScheduler_1_1VruntimeCompare.html", null ],
    [ "TaskControlBlock::WakeTickCompare", "structTaskControlBlock_1_1WakeTickCompare.html", null ],
    [ "acpi::Acpi::Xsdt", "structacpi_1_1Acpi_1_1Xsdt.html", null ]
];