name: CMake

on: 
  - push
  - pull_request
  - release

env:
  BUILD_TYPE: Release

jobs:
  build_macos:
    runs-on: macos-latest

    steps:
    - name: Get code
      uses: actions/checkout@v2
      
    - name: Setup brew
      shell: bash
      run: |
        brew install x86_64-elf-binutils
        brew install x86_64-elf-gcc
        brew install wget
#        brew install automake
#        brew install autogen

#     - name: Setup grub
#       shell: bash
#       run: |
#         sh ${{github.workspace}}/tools/grub4mac.sh
#         export PATH="${{github.workspace}}/tools/grub-2.04/build/grub/bin:$PATH"

    - name: Make build dir
      shell: bash
      run: |
        mkdir ${{github.workspace}}/build

    - name: cmake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake -TOOLCHAIN_PREFIX=x86_64-elf- -DCMAKE_C_COMPILER=x86_64-elf-gcc -DCMAKE_CXX_COMPILER=x86_64-elf-g++ -DCMAKE_OBJCOPY=x86_64-elf-objcpy -DPLATFORM=bochs -DARCH=x86_64 ..

    - name: make
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: make
    
#   build_ubuntu:
#     runs-on: ubuntu-latest
    

#   build_win:
#     runs-on: windows-latest
