name: CMake

on: 
  - push
  - pull_request
  - release

env:
  BUILD_TYPE: Release

jobs:
  build_macos:
    runs-on: macos-latest

    steps:
    - name: Setup brew
      shell: bash
      run: |
        brew install x86_64-elf-binutils
        brew install x86_64-elf-gcc
        brew install autogen
        brew install wget

    - name: Setup grub
      shell: bash
      run: |
        sh ${{github.action_path}}/tools/grub4mac.sh

    - name: cmake
      shell: bash
      working-directory: ${{github.action_path}}/build
      run: cmake -DCMAKE_TOOLCHAIN_FILE=${{github.action_path}}/cmake/toolchain_mac_x86_64.cmake -DPLATFORM=bochs -DARCH=x86_64 ..

    - name: make
      shell: bash
      working-directory: ${{github.action_path}}/build
      run: make
    
#   build_ubuntu:
#     runs-on: ubuntu-latest
    

#   build_win:
#     runs-on: windows-latest
