# Copyright The SimpleKernel Contributors

name: build

on:
  - push
  - pull_request
  - release

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: x86_64
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            cmake --preset=build_x86_64
            cmake --build build_x86_64 --target SimpleKernel unit-test coverage docs

      - name: riscv64
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            cmake --preset=build_riscv64
            cmake --build build_riscv64 --target SimpleKernel

      - name: aarch64
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            cmake --preset=build_aarch64
            cmake --build build_aarch64 --target SimpleKernel

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ${{ github.workspace }}/build_x86_64/coverage/coverage.info
          verbose: true

      - name: Publish
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.workspace }}/docs/html
